In [1]:
import numpy as np

tup = tuple(map(int, input().split()))

zero = np.zeros(tup, dtype=int)
one = np.ones(tup, dtype=int)
print(zero)
print(one)

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
